In [2]:
import polars as pl
import pandas as pd

In [3]:
tracking_df = pd.read_hdf("tracking_results/DeepEcoHAB_20260501_211615_007DLC_DekrW18_the_future_of_EcohabNov22shuffle1_snapshot_best-260_el.h5")

long_pdf = (
    tracking_df
    .stack(["scorer", "individuals", "bodyparts"])
    #.rename(["x","y"])
    .reset_index()
)
tracking_lf = pl.from_pandas(long_pdf).lazy().rename({'level_0':"frame"}).drop('scorer') #ograć rename wczytywaniem z hdf

/tmp/ipykernel_179866/1046192953.py:5: FutureWarning: The previous implementation of stack is deprecated and will be removed in a future version of pandas. See the What's New notes for pandas 2.1.0 for details. Specify future_stack=True to adopt the new implementation and silence this warning.
  .stack(["scorer", "individuals", "bodyparts"])

In [4]:
tracking_lf.head().collect()

shape: (5, 6)
┌───────┬─────────────┬───────────┬────────────┬────────────┬────────────┐
│ frame ┆ individuals ┆ bodyparts ┆ x          ┆ y          ┆ likelihood │
│ ---   ┆ ---         ┆ ---       ┆ ---        ┆ ---        ┆ ---        │
│ i64   ┆ str         ┆ str       ┆ f64        ┆ f64        ┆ f64        │
╞═══════╪═════════════╪═══════════╪════════════╪════════════╪════════════╡
│ 0     ┆ ind1        ┆ Dorsal1   ┆ 780.426636 ┆ 282.12326  ┆ 0.383084   │
│ 0     ┆ ind1        ┆ Dorsal2   ┆ 780.251953 ┆ 292.798309 ┆ 0.383084   │
│ 0     ┆ ind1        ┆ Dorsal3   ┆ 782.416443 ┆ 306.688049 ┆ 0.383084   │
│ 0     ┆ ind1        ┆ Dorsal4   ┆ 782.880493 ┆ 318.88559  ┆ 0.383084   │
│ 0     ┆ ind1        ┆ Ear_left  ┆ 776.271545 ┆ 279.346252 ┆ 0.383084   │
└───────┴─────────────┴───────────┴────────────┴────────────┴────────────┘

In [16]:

tracking_lf = tracking_lf.filter(
    pl.col('bodyparts') == "Dorsal2",#to decide, maybe centroid instead
).drop(pl.col("likelihood"))#.collect()

In [6]:
antenna_df = pl.scan_csv(
    "tracking_results/DeepEcoHAB_20260501_211615_antenna_data.csv", 
    has_header=False,
    separator=";",
    new_columns=['antenna', 'tag', 'timestamp', 'datetime'],
    infer_schema_length=1000
    ).with_columns(
        pl.col('timestamp').str.to_integer(base=16)
    )

video_index = 7 #to extract from filename suffix
frames_per_video = 108000

antenna_df = antenna_df.with_columns(
    (pl.col('antenna')==10).cum_sum().alias('frame')
).filter(
    pl.col('frame').is_between(frames_per_video*video_index, frames_per_video*(video_index+1)-1)
).with_columns(
    (pl.col('frame')-pl.col('frame').first()).alias('frame')
)

In [7]:
antenna_df.collect().to_pandas()

        antenna       tag  timestamp                    datetime   frame
0            10  01000000   13881021  2026-05-02T04:16:25.187506       0
1            10  01000000   13881025  2026-05-02T04:16:25.234955       1
2            10  01000000   13881028  2026-05-02T04:16:25.267095       2
3            10  01000000   13881031  2026-05-02T04:16:25.299101       3
4            10  01000000   13881035  2026-05-02T04:16:25.330489       4
...         ...       ...        ...                         ...     ...
115307       10  01000000   14241014  2026-05-02T05:16:25.269040  107995
115308       10  01000000   14241017  2026-05-02T05:16:25.300795  107996
115309       10  01000000   14241021  2026-05-02T05:16:25.341808  107997
115310       10  01000000   14241024  2026-05-02T05:16:25.371307  107998
115311       10  01000000   14241027  2026-05-02T05:16:25.401579  107999

[115312 rows x 5 columns]

In [37]:
antenna_df.filter(pl.col('tag')=='02000000').collect().to_pandas()

   antenna       tag  timestamp                    datetime  frame
0        1  02000000   14053249  2026-05-02T04:45:07.549451  51667

In [8]:
animal_detections = antenna_df.filter(
    pl.col("antenna") != 10#remove magic string
)

In [ ]:
animal_detections.collect().to_pandas()

      antenna       tag  timestamp                    datetime   frame
0           5  F02AE61A   13883423  2026-05-02T04:16:49.228317     721
1           5  F02AE61A   13883427  2026-05-02T04:16:49.269069     722
2           5  F02AE61A   13883431  2026-05-02T04:16:49.300830     723
3           5  F02AE61A   13883435  2026-05-02T04:16:49.348346     724
4           5  F02AE61A   13883439  2026-05-02T04:16:49.380227     725
...       ...       ...        ...                         ...     ...
7307        1  F02AE61A   14235857  2026-05-02T05:15:33.706488  106448
7308        1  F02AE61A   14235861  2026-05-02T05:15:33.737894  106449
7309        1  F02AE61A   14235865  2026-05-02T05:15:33.785172  106450
7310        1  F02AE61A   14235869  2026-05-02T05:15:33.826882  106451
7311        1  F02AE61A   14235873  2026-05-02T05:15:33.870102  106453

[7312 rows x 5 columns]

In [15]:
animal_detections = animal_detections.with_columns(
    (
        pl.struct(["antenna", "tag"]).ne(pl.struct(["antenna", "tag"]).shift())
        | pl.col("frame").diff().gt(5)
    )
    .cum_sum()
    .cast(pl.Int16)
    .alias("run_id")
    .fill_null(0)
)
animal_detections.collect().to_pandas()
#group by run id of antenna and tag, with columns under antenna - in the future take the actual timestamp instead of frame

,antenna,tag,timestamp,datetime,frame,run_id,jump
0,5,F02AE61A,13883423,2026-05-02T04:16:49.228317,721,0,NaN
1,5,F02AE61A,13883427,2026-05-02T04:16:49.269069,722,0,0.0
2,5,F02AE61A,13883431,2026-05-02T04:16:49.300830,723,0,0.0
3,5,F02AE61A,13883435,2026-05-02T04:16:49.348346,724,0,0.0
4,5,F02AE61A,13883439,2026-05-02T04:16:49.380227,725,0,0.0
...,...,...,...,...,...,...,...
7307,1,F02AE61A,14235857,2026-05-02T05:15:33.706488,106448,1459,948.0
7308,1,F02AE61A,14235861,2026-05-02T05:15:33.737894,106449,1459,948.0
7309,1,F02AE61A,14235865,2026-05-02T05:15:33.785172,106450,1459,948.0
7310,1,F02AE61A,14235869,2026-05-02T05:15:33.826882,106451,1459,948.0
7311,1,F02AE61A,14235873,2026-05-02T05:15:33.870102,106453,1459,948.0

In [22]:
antenna_with_coords = animal_detections.join(
    tracking_lf,
    on = 'frame',
    how = 'left'
)

In [24]:
antenna_with_coords.collect()

shape: (51_541, 11)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ antenna ┆ tag      ┆ timestamp ┆ datetime   ┆ … ┆ individual ┆ bodyparts ┆ x         ┆ y         │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ s          ┆ ---       ┆ ---       ┆ ---       │
│ i64     ┆ str      ┆ i64       ┆ str        ┆   ┆ ---        ┆ str       ┆ f64       ┆ f64       │
│         ┆          ┆           ┆            ┆   ┆ str        ┆           ┆           ┆           │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind1       ┆ Dorsal2   ┆ 1044.8079 ┆ 744.28918 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆ 83        ┆ 5         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind2       ┆ Dorsal2   ┆ 685.25231 ┆ 483.83154 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆ 9         ┆ 3         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind3       ┆ Dorsal2   ┆ 708.65899 ┆ 480.56555 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆ 7         ┆ 2         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind4       ┆ Dorsal2   ┆ 711.78601 ┆ 360.19119 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆ 1         ┆ 3         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind5       ┆ Dorsal2   ┆ 201.81424 ┆ 310.67059 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆           ┆ 3         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ …       ┆ …        ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 1       ┆ F02AE61A ┆ 14235873  ┆ 2026-05-02 ┆ … ┆ ind4       ┆ Dorsal2   ┆ 711.82757 ┆ 360.73141 │
│         ┆          ┆           ┆ T05:15:33. ┆   ┆            ┆           ┆ 6         ┆ 5         │
│         ┆          ┆           ┆ 870102     ┆   ┆            ┆           ┆           ┆           │
│ 1       ┆ F02AE61A ┆ 14235873  ┆ 2026-05-02 ┆ … ┆ ind5       ┆ Dorsal2   ┆ 1131.4671 ┆ 946.46881 │
│         ┆          ┆           ┆ T05:15:33. ┆   ┆            ┆           ┆ 63        ┆ 1         │
│         ┆          ┆           ┆ 870102     ┆   ┆            ┆           ┆           ┆           │
│ 1       ┆ F02AE61A ┆ 14235873  ┆ 2026-05-02 ┆ … ┆ ind6       ┆ Dorsal2   ┆ 389.52276 ┆ 170.75901 │
│         ┆          ┆           ┆ T05:15:33. ┆   ┆            ┆           ┆ 6         ┆ 8         │
│         ┆          ┆           ┆ 870102     ┆   ┆            ┆           ┆           ┆           │
│ 1       ┆ F02AE61A ┆ 14235873  ┆ 2026-05-02 ┆ … ┆ ind7       ┆ Dorsal2   ┆ 170.02368 ┆ 366.71713 │
│         ┆          ┆           ┆ T05:15:33. ┆   ┆            ┆           ┆ 2         ┆ 3         │
│         ┆          ┆           ┆ 870102     ┆   ┆            ┆           ┆           ┆           │
│ 1       ┆ F02AE61A ┆ 14235873  ┆ 2026-05-02 ┆ … ┆ ind8       ┆ Dorsal2   ┆ 998.46838 ┆ 1063.2574 │
│         ┆          ┆           ┆ T05:15:33. ┆   ┆            ┆           ┆ 4         ┆ 46        │
│         ┆          ┆           ┆ 870102     ┆   ┆            ┆           ┆           ┆           │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
antenna_with_coords = antenna_with_coords.filter((pl.col('tag') != '02000000') & (pl.col('tag') != '02000060')) #maybe use sanitation for that

shape: (64, 11)
┌─────────┬──────────┬───────────┬────────────┬───┬────────────┬───────────┬───────────┬───────────┐
│ antenna ┆ tag      ┆ timestamp ┆ datetime   ┆ … ┆ individual ┆ bodyparts ┆ x         ┆ y         │
│ ---     ┆ ---      ┆ ---       ┆ ---        ┆   ┆ s          ┆ ---       ┆ ---       ┆ ---       │
│ i64     ┆ str      ┆ i64       ┆ str        ┆   ┆ ---        ┆ str       ┆ f64       ┆ f64       │
│         ┆          ┆           ┆            ┆   ┆ str        ┆           ┆           ┆           │
╞═════════╪══════════╪═══════════╪════════════╪═══╪════════════╪═══════════╪═══════════╪═══════════╡
│ 5       ┆ 12F5FF19 ┆ 13885333  ┆ 2026-05-02 ┆ … ┆ ind3       ┆ Dorsal2   ┆ 709.22869 ┆ 480.14028 │
│         ┆          ┆           ┆ T04:17:08. ┆   ┆            ┆           ┆ 9         ┆ 9         │
│         ┆          ┆           ┆ 327221     ┆   ┆            ┆           ┆           ┆           │
│ 7       ┆ DD43E61A ┆ 14104219  ┆ 2026-05-02 ┆ … ┆ ind3       ┆ Dorsal2   ┆ 968.24444 ┆ 1129.3752 │
│         ┆          ┆           ┆ T04:53:37. ┆   ┆            ┆           ┆ 6         ┆ 44        │
│         ┆          ┆           ┆ 265555     ┆   ┆            ┆           ┆           ┆           │
│ 9       ┆ D5969C1A ┆ 13917756  ┆ 2026-05-02 ┆ … ┆ ind8       ┆ Dorsal2   ┆ 492.47439 ┆ 1011.5698 │
│         ┆          ┆           ┆ T04:22:32. ┆   ┆            ┆           ┆ 6         ┆ 24        │
│         ┆          ┆           ┆ 585646     ┆   ┆            ┆           ┆           ┆           │
│ 4       ┆ 6D68A819 ┆ 13985911  ┆ 2026-05-02 ┆ … ┆ ind8       ┆ Dorsal2   ┆ 246.58947 ┆ 270.26840 │
│         ┆          ┆           ┆ T04:33:54. ┆   ┆            ┆           ┆ 8         ┆ 2         │
│         ┆          ┆           ┆ 137450     ┆   ┆            ┆           ┆           ┆           │
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind7       ┆ Dorsal2   ┆ 685.25231 ┆ 483.83154 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆ 9         ┆ 3         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ …       ┆ …        ┆ …         ┆ …          ┆ … ┆ …          ┆ …         ┆ …         ┆ …         │
│ 7       ┆ 0265E61A ┆ 13896093  ┆ 2026-05-02 ┆ … ┆ ind2       ┆ Dorsal2   ┆ 972.56433 ┆ 778.14447 │
│         ┆          ┆           ┆ T04:18:55. ┆   ┆            ┆           ┆ 1         ┆           │
│         ┆          ┆           ┆ 935333     ┆   ┆            ┆           ┆           ┆           │
│ 4       ┆ 6D68A819 ┆ 13985911  ┆ 2026-05-02 ┆ … ┆ ind2       ┆ Dorsal2   ┆ 423.87249 ┆ 133.62448 │
│         ┆          ┆           ┆ T04:33:54. ┆   ┆            ┆           ┆ 8         ┆ 1         │
│         ┆          ┆           ┆ 137450     ┆   ┆            ┆           ┆           ┆           │
│ 5       ┆ F02AE61A ┆ 13883423  ┆ 2026-05-02 ┆ … ┆ ind4       ┆ Dorsal2   ┆ 711.78601 ┆ 360.19119 │
│         ┆          ┆           ┆ T04:16:49. ┆   ┆            ┆           ┆ 1         ┆ 3         │
│         ┆          ┆           ┆ 228317     ┆   ┆            ┆           ┆           ┆           │
│ 4       ┆ 6D68A819 ┆ 13985911  ┆ 2026-05-02 ┆ … ┆ ind1       ┆ Dorsal2   ┆ 1021.4743 ┆ 1041.8247 │
│         ┆          ┆           ┆ T04:33:54. ┆   ┆            ┆           ┆ 65        ┆ 07        │
│         ┆          ┆           ┆ 137450     ┆   ┆            ┆           ┆           ┆           │
│ 9       ┆ D5969C1A ┆ 13917756  ┆ 2026-05-02 ┆ … ┆ ind4       ┆ Dorsal2   ┆ 411.09713 ┆ 117.31184 │
│         ┆          ┆           ┆ T04:22:32. ┆   ┆            ┆           ┆ 7         ┆ 4         │
│         ┆          ┆           ┆ 585646     ┆   ┆            ┆           ┆           ┆           │
└─────────┴──────────┴───────────┴────────────┴───┴────────────┴───────────┴───────────┴───────────┘

In [ ]:
antenna_with_coords.group_by(
    ['run_id', 'tag', 'individuals']
).agg(
    pl.col("x").mean(),
    pl.col("y").mean(),
)